name = "SpikeNetOpt"
uuid = "145ac929-eb8f-4c2d-a659-99b6ac427599"
authors = ["Russell Jarvis <russelljarvis@protonmail.com>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SpikingNeuralNetworks = "9d8b7fda-1049-58bc-9481-071a9f369938"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WaspNet = "c0b53cd3-4946-4106-b8e7-91971464ade9"

[compat]
UnicodePlots = "1.3.0"
julia = "1.5.3"-"1.6.2"
